name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ToDo_Project/ToDo_Project.sln

      - name: Build
        run: dotnet build ToDo_Project/ToDo_Project.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ToDo_Project.Tests/ToDo_Project.Tests.csproj --no-build --verbosity normal
